Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo perl -pi.bak -e 's/archive.ubuntu.com/de.archive.ubuntu.com/' /etc/apt/sources.list
    sudo sh -c 'echo deb http://packages.erlang-solutions.com/ubuntu wily contrib >> /etc/apt/sources.list'
    wget http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    sudo apt-key add erlang_solutions.asc
    sudo apt-get update

    sudo apt-get install -y git emacs24-nox autoconf autoconf-archive libtool build-essential nodejs npm texlive-full python-sphinx openjdk-7-jre-headless shunit2 libmozjs185-dev libicu-dev esl-erlang libcurl4-openssl-dev
    sudo npm install -g npm
    sudo ln -s /usr/bin/nodejs /usr/bin/node

  SHELL
end
