Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y git emacs-nox autoconf autoconf-archive libtool build-essential nodejs npm texlive-full python-sphinx openjdk-7-jre-headless shunit2 libmozjs185-dev libicu-dev erlang
    sudo npm install -g npm
  SHELL
end
