Vagrant.configure(2) do |config|
  config.vm.box = "freebsd/FreeBSD-10.2-RELEASE"
  config.vm.base_mac = "080027D14C66"
  config.vm.network "public_network", bridge: "en0: Ethernet"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.ssh.shell = "sh"

  config.vm.provision "shell", inline: <<-SHELL
    pkg install -y git emacs-nox11 autoconf autoconf-archive libtool gmake node npm texlive-full python py27-sphinx openjdk-jre spidermonkey185 icu erlang
    npm install -g npm
  SHELL
end
