Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo sh -c 'deb http://packages.erlang-solutions.com/ubuntu trusty contrib >> /etc/apt/sources.list'
    wget http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    sudo apt-key add erlang_solutions.asc
    sudo apt-get update

    sudo apt-get install git emacs23-nox autoconf autoconf-archive libtool build-essential nodejs npm texlive-full python-sphinx openjdk-7-jre-headless shunit2 libmozjs185-dev libicu-dev esl-erlang

  SHELL
end
