Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo sh -c 'echo deb http://http.debian.net/debian wheezy-backports main > /etc/apt/sources.list.d/wheezy-backports.list'
    sudo apt-get -qq update
    sudo apt-get install -y git emacs23-nox autoconf autoconf-archive libtool build-essential nodejs-legacy texlive-full python-sphinx openjdk-7-jre-headless shunit2 libmozjs185-dev libicu-dev libcurl4-openssl-dev erlang/wheezy-backports
    sudo sh -c 'curl https://www.npmjs.com/install.sh | sh'
  SHELL
end
